Updated and Simplified Steps for Installation🤓
RaphProductions/macOS-t460 pull request #3
Opened 2023-12-21 14:19 UTC by AsherCarneiro

- Updated Readme.md for better installation
- Simplified a lot of steps
- Added some extra resources for when stuck during installation

**_Have a great day!_**

2023-12-21 14:20 UTC, AsherCarneiro commented
also you should probably update the EFI with newer versions of kexts, the older one's don't seem to work in late 2023.

2024-02-27 22:33 UTC, RaphMar2021 requested changes
I like how you modified the guide. But i will still wait for some changes on the lines that i reviewed. (1, 26, 66)

2024-02-27 22:33 UTC, RaphMar2021 commented on README.md
> +# MacOS Kit from OS11 to 13 💻
I don't really like this title, maybe change to 'macOS 11-13 for ThinkPad T460'?

2024-02-27 22:33 UTC, RaphMar2021 commented on README.md
> +Open Rufus (cause balenaetcher doesn't work some times for no particular reason) and select these options :
Why the BalenaEtcher mention? I included this step because we can't format large USB flash drives to FAT32 natively with Windows.

2024-02-27 22:33 UTC, RaphMar2021 commented on README.md
> +### 5 : Connect your laptop to the WI-FI or Ethernet
Why not remplacing 'the WIFI or Ethernet' with simply 'Internet'?

2024-05-21 15:52 UTC, RaphProductions commented
Since the pull request hasn't been updated for ~3 months, i will close this pull request. Please ask me if you want me to reopen the pull request so you can do the changes.

2024-05-21 15:52 UTC, closed without merging

2024-06-10 15:37 UTC, AsherCarneiro commented
yo @RaphProductions  i forgot about this pr i made sry, i made the requested changes in my main can you reopen if possible.